//
// Created by Ivan Bogun on 3/30/15.
//

#ifndef ROBUST_TRACKING_BY_DETECTION_OBJECTNESSTEST_H
#define ROBUST_TRACKING_BY_DETECTION_OBJECTNESSTEST_H


class ObjectnessTest {

};


#endif //ROBUST_TRACKING_BY_DETECTION_OBJECTNESSTEST_H
