function [ names ] = getSequenceNamesOTB100(  )
%GETSEQUENCENAMESOTB100 Summary of this function goes here
%   Detailed explanation goes here

names = {'Basketball.json' , 'Biker.json' , 'Bird1.json' , 'Bird2.json' ,...
    'BlurBody.json' , 'BlurCar1.json' , 'BlurCar2.json' , 'BlurCar3.json' , ...
    'BlurCar4.json' , 'BlurFace.json' , 'BlurOwl.json' , 'Board.json' ,...
    'Bolt.json' , 'Bolt2.json' , 'Box.json' , 'Boy.json' , 'Car1.json' , ...
    'Car2.json' , 'Car24.json' , 'Car4.json' , 'CarDark.json' , ...
    'CarScale.json' , 'ClifBar.json' , 'Coke.json' , 'Couple.json' , ...
    'Coupon.json' , 'Crossing.json' , 'Crowds.json' , 'Dancer.json' , ...
    'Dancer2.json' , 'David.json' , 'David2.json' , 'David3.json' , ...
    'Deer.json' , 'Diving.json' , 'Dog.json' , 'Dog1.json' , ...
    'Doll.json' , 'DragonBaby.json' , 'Dudek.json' , 'FaceOcc1.json' ,...
    'FaceOcc2.json' , 'Fish.json' , 'FleetFace.json' , 'Football.json' ,...
    'Football1.json' , 'Freeman1.json' , 'Freeman3.json' , ...
    'Freeman4.json' , 'Girl.json' , 'Girl2.json' , 'Gym.json' , ...
    'Human2.json' , 'Human3.json' , 'Human4.json' , 'Human5.json' ,...
    'Human6.json' , 'Human7.json' , 'Human8.json' , 'Human9.json' ,...
    'Ironman.json' , 'Jogging-1.json' , 'Jogging-2.json' , 'Jump.json' ,...
    'Jumping.json' , 'KiteSurf.json' , 'Lemming.json' , 'Liquor.json' , ...
    'Man.json' , 'Matrix.json' , 'Mhyang.json' , 'MotorRolling.json' ,...
    'MountainBike.json' , 'Panda.json' , 'RedTeam.json' , 'Rubik.json' , ...
    'Shaking.json' , 'Singer1.json' , 'Singer2.json' , 'Skater.json' ,...
    'Skater2.json' , 'Skating1.json' , 'Skating2-1.json' , ...
    'Skating2-2.json' , 'Skiing.json' , 'Soccer.json' , ...
    'Subway.json' , 'Surfer.json' , 'Suv.json' , 'Sylvester.json' , ...
    'Tiger1.json' , 'Tiger2.json' , 'Toy.json' , 'Trans.json' , ...
    'Trellis.json' , 'Twinnings.json' , 'Vase.json' , 'Walking.json' ,...
    'Walking2.json' , 'Woman.json'};

for i=1:length(names)
    s = names{i};
    names{i} = s(1:length(s)-5);
end

end

